### ISSUE TITLE
LP problems stopping because of numerical error

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#161] opened 2019-12-12 22:34 UTC
While looking at Gurobi output, I noticed that some specifications I have been trying have LP problems that terminate (after quite some time) with "numeric error".

Specifically, in my case, the lower bound (which is solved first) terminated with this numerical error, and then the upper bound converged on a solution. `ivmte` then told me that `LP solutions are unbounded` and restarted the audit with an expanded initial grid. I have two questions:

1. Since the lower bound doesn't converge, we already know that `ivmte` will have to expand the grid and reiterate. In this case, is there any reason for `ivmte` to estimate the upper bound? (Ideally, estimation would always be fast enough for it not to matter, but in my case, these LP problems are taking 2-3 hours each.)

2. If my implied specification has these numerical issues, is there anything I can do besides expanding the size of the grid and hoping for the best?

**Comment by a-torgovitsky** [comment] 2019-12-12 23:20
Can you give a sense of what the specifications look like?
What are `m0` and `m1` and `ivlike`?
How many variables/constraints are there when they run it with Gurobi standalone?

I'm a bit surprised that you are running into programs large enough to take 2--3 hours, let alone have numerical problems.

**Comment by johnnybonney** [comment] 2019-12-13 01:33
- `m0` and `m1` both take the following form:
```
~factor(FE) + X1 + ... + X10 +
    factor(FE):uSpline(degree = 3, knots = c(0.25, 0.5, 0.75)) +
    X1:uSpline(degree = 3, knots = c(0.25, 0.5, 0.75)) +
    ... +
    X10:uSpline(degree = 3, knots = c(0.25, 0.5, 0.75))
```
where `FE` takes 10 values and `X1`, ..., `X10` (which are linearly interacted with the splines) are all continuous covariates.

- `ivlike` contains the slope moments from a reduced form regression where the instrument (which takes 5 values) is fully interacted with `FE` (38 moments).

- `initgrid.nx = 1816` and `initgrid.nu = 25`

Gurobi says the LP problem has 294,231 rows (constraints) and 382 columns (variables). Interestingly, when I run the problem in Gurobi directly, it converges in ~10 minutes, as opposed to calling Gurobi through R/`ivmte` (when it takes 2-3 hours and does not converge).

**Comment by a-torgovitsky** [comment] 2019-12-13 03:23
Uh, the last thing you said is super concerning. The Gurobi R API should just be calling Gurobi!

@jkcshea could you try to bug check this by:
a) Writing out the inputs of the LP (the matrices/vectors) to file, as well as the .mps file -- @johnnybonney can you send a replication kit to do this?
b) Writing a short R script that loads the LP inputs (matrices/vectors) and calls the R Gurobi API.
then comparing it to
c) Running Gurobi directly on the .mps

If a) + b) are much different than c), and that's what I am anticipating, then I think we have a Gurobi bug on our hands. If so, we should report it to them --- they are very responsive to bugs like this.

**Comment by a-torgovitsky** [comment] 2019-12-13 03:24
Also @johnnybonney , what are the shape constraints here?
And what is the size of the constraint grid?
294K constraints arising from 38 moments seems like a lot!

**Comment by johnnybonney** [comment] 2019-12-13 17:25
[Here is a zip file](https://github.com/jkcshea/ivmte/files/3961925/dinkelman_example.zip) with data and an R script that reproduces the specification I was using and should reproduce the behavior I was seeing. (Let me know if that doesn't seem to be the case!)

@a-torgovitsky -- I don't impose any shape constraints besides the default constraints on the
 upper and lower bounds for `m0` and `m1`. The constraint grid has `initgrid.nx = 1816` and `initgrid.nu = 25`, so 45,400 points.

**Comment by a-torgovitsky** [comment] 2019-12-13 17:45
Hmm, 45,400 x 4 = 181K
We are still short about 100K constraints?

**Comment by jkcshea** [comment] 2019-12-13 18:19
Oh, but we have default upper/lower bounds for
1. m0
2. m1
3. mte

I also caught a mistake I made: `initgrid.nu` currently reflects the number of draws from a Halton sequence. I then add on the end points `{0, 1}`. So actually, there are `initgrid.nu + 2 = 27` points for `u`.

That would give us `1816 * 27 * 6 = 294,192` shape constraints.

If you add the 38 moments and the criterion, we get @johnnybonney's count of 294,231.

**Comment by a-torgovitsky** [comment] 2019-12-13 18:58
Got it.
But if m0 and m1 are at their default bounds, isn't it redundant to also put bounds on mte?

For example, suppose that Y is binary, and that the user doesn't pass anything.
Then we infer m0.lb = 0, m1.lb = 0, m0.ub and m1.ub = 1.

Adding mte.lb = -1 and mte.ub = 1 shouldn't change anything, should it?

**Comment by jkcshea** [comment] 2019-12-13 19:32
Ah good point.

I'll remove those default constraints on the MTE, then.

I'll also go ahead and delete the last line of the following code from the vignette:

https://github.com/jkcshea/ivmte/blob/261df661ab9e264c927022c6ba963b43f8461a88/vignettes/ivmte.Rmd#L300-L307

**Comment by a-torgovitsky** [comment] 2019-12-13 19:52
I don't think it's necessary to change the vignette.

It's still true -- we are just coding intelligently by noticing that these constraints will never bind.
That is true, right?

**Comment by jkcshea** [comment] 2019-12-13 20:17
That is indeed true.
Okay, vignette remains as is.

**Comment by jkcshea** [comment] 2019-12-14 17:50
Unfortunately, my gurobi expired overnight.
I can't renew it since the university's VPN for Linux doesn't seem to be working (stuck at an airport now).
This makes debugging hard.

Nevertheless, I am able to confirm that for the _initial_ audit, R and Gurobi match when minimizing the criterion, and finding the lower bound.
**For the lower bound, Gurobi was also returning numerical errors.**
I had to leave Chicago before the upper bound could complete, but R and Gurobi were behaving very similarly.

@johnnybonney When you compared the R API against Gurobi, did you feed Gurobi the .mps file returned by `ivmte` _after_ you had let R run for 3 hours?
I ask because `ivmte` will update the .mps files with every iteration of the audit.
`ivmte` may have taken 3 hours to run because it was repeatedly encountering numerical errors, and had to restart the audit with an expanded grid.
The .mps file will only reflect the final iteration of the audit, thus requiring much less time.

**Comment by johnnybonney** [comment] 2019-12-16 18:11
> When you compared the R API against Gurobi, did you feed Gurobi the .mps file returned by ivmte after you had let R run for 3 hours?

No. I did not even let R move on to the second audit -- I cut it off before it re-calculated the minimum criterion, so I can confirm that the MPS file I was using was from the first audit. The comparison of the R API to standalone Gurobi was for the same LP problem.

> `ivmte` may have taken 3 hours to run because it was repeatedly encountering numerical errors, and had to restart the audit with an expanded grid.

This was not the case. To be clear: `ivmte` did not take 3 hours -- it would have taken even longer. The single LP problem for the lower bound in the initial audit took 3 hours. The initial audit itself took about 4 hours. 

I imagine you ran the replication after updating the package to remove the MTE upper/lower bound constraints. I just updated the package (with the MTE upper/lower bound constraints removed), and now the R API and Gurobi perform similarly.

Additionally, the same problem that took ~3 hours before now takes 20 seconds (before returning a numerical error) -- a massive improvement as far as run-time goes. I am surprised that removing the redundant constraints has such an impact.

-------------------------------
Since at this point, I don't see any more evidence of the R API and Gurobi performing differently, I wanted to come back to my initial questions:
1. If the lower bound doesn't converge, we already know that `ivmte` will have to expand the grid and reiterate. In this case, is there any reason for `ivmte` to estimate the upper bound? (this would purely be to increase speed in such cases)
2. If my implied specification has these numerical issues, is there anything I can do besides expanding the size of the grid and hoping for the best? (Since the error is due to numerical issues, should I really expect expanding the grid to fix the problem?)

**Comment by jkcshea** [comment] 2019-12-17 11:40
> I imagine you ran the replication after updating the package to remove the MTE upper/lower bound constraints. 

Ah yes, you are right.
It looks like we are now matching.

> 1. If the lower bound doesn't converge, we already know that ivmte will have to expand the grid and reiterate. In this case, is there any reason for ivmte to estimate the upper bound? (this would purely be to increase speed in such cases)

That's a good point, I can certainly implement that.
I'm still waiting on the University to get back to me regarding my VPN issues, though.
So I currently cannot implement this fix for Gurobi, but can do it for lpSolveAPI and CPLEX.

I also noticed that CPLEX doesn't run into any problems with your example.
The total run time was about 40 minutes.
Here is the output:

```RPerforming audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.2499799
    Obtaining bounds...
    Violations:  124 
    Expanding constraint grid to include 100 additional points...

    Audit count: 2
    Minimum criterion: 0.2505304
    Obtaining bounds...
    Violations:  49 
    Expanding constraint grid to include 49 additional points...

    Audit count: 3
    Minimum criterion: 0.2506794
    Obtaining bounds...
    Violations:  10 
    Expanding constraint grid to include 10 additional points...

    Audit count: 4
    Minimum criterion: 0.2506807
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [0.007320936, 0.01460951]
```
> 2. If my implied specification has these numerical issues, is there anything I can do besides expanding the size of the grid and hoping for the best? (Since the error is due to numerical issues, should I really expect expanding the grid to fix the problem?)

I agree that expanding the grid doesn't quite make sense.Maybe it would be better to simply stop the procedure, then.
@a-torgovitsky will be more informed on this, though.

**Comment by a-torgovitsky** [comment] 2019-12-17 14:25
Could you post the Gurobi output where it runs into a numerical error?
I wonder if this might be a rare scaling issue that is popping up.

**Comment by johnnybonney** [comment] 2019-12-17 16:30
Here is the Gurobi output:

```
Gurobi Optimizer version 9.0.0 build v9.0.0rc2 (win64)
Optimize a model with 196167 rows, 382 columns and 9586886 nonzeros
Model fingerprint: 0x426539ca
Coefficient statistics:
  Matrix range     [1e-13, 6e+02]
  Objective range  [8e-05, 4e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [6e-05, 5e-01]
Warning: Model contains large matrix coefficient range
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.
Presolve time: 4.51s
Presolved: 382 rows, 196167 columns, 9586886 nonzeros

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -0.0000000e+00   3.018467e+01   7.448738e+11     10s
Warning: 1 variables dropped from basis
Warning: switch to quad precision
Warning: 1 variables dropped from basis
Warning: 1 variables dropped from basis
Warning: 1 variables dropped from basis
     223   -2.2221895e-01   7.919086e+00   3.380531e+11     10s
Warning: 1 variables dropped from basis
Warning: 1 variables dropped from basis

Stopped in 495 iterations and 15.85 seconds
Numeric error
```

**Comment by a-torgovitsky** [comment] 2019-12-17 18:07
Seems to be poorly conditioned.
@jkcshea any idea why we are still having these problems with coefficient ranges?

**Comment by jkcshea** [comment] 2019-12-18 00:10
[Here](https://github.com/jkcshea/ivmte/issues/108#issuecomment-545665003) we begin to discuss scaling issues.
However, we ultimately decided that we would not directly deal with scaling issues, and to remove all warning messages.
Instead, everything would be relegated to the Debug mode ([here](https://github.com/jkcshea/ivmte/issues/108#issuecomment-546347277)).

I suspect the scaling issues are stemming from a combination of the propensity scores, IV-like estimands, and the MTR specifications.
I'll see if I can track down where exactly.

**Comment by a-torgovitsky** [comment] 2019-12-18 01:37
Ok yeah I think we still need to figure out the root cause of this, since it's a recurring issue.

**Comment by jkcshea** [comment] 2019-12-19 04:35
The tiny coefficients in the constraint matrix stem from the equality constraints for two variables and their interactions with splines.:
1. `prop_indianwhite0`
1. `factor(dccode0)`

In the case of `prop_indianwhite0`, that variable is 0 for 60% of the observations.
For the rest, the value is very small, the grand mean being only 0.00126.
Consequently, when interacted with the splines and then averaged, we get really small numbers.

In the case of `factor(dccode0)`, it appears to be an issue with precision of 0s.
For example, for `dccode0 = 25`, all propensity scores are within the interval `(0.25, 0.75)`.
The spline it is interacted with has internal knots `c(0.25, 0.5, 0.75)`, and is degree 3.
So when constructing the gamma moments, the integral of the first basis spline (which is only non-zero over the region `[0, 0.25]`) and the last basis spline (which is only non-zero over the region `[0.75, 1]`) should be 0 for individuals with `dccode0 = 25`.
However, these zeros are stored as values like `8e-13`.
So once averaging over the sample, we get tiny numbers.

This second example extends to other subsamples, e.g. `dccode0 = 23` has 0 cases with propensity score greater than 0.50.

**Comment by jkcshea** [comment] 2019-12-19 06:49
Resolving this will be very straightforward.

**Comment by jkcshea** [comment] 2019-12-29 14:34
Sorry, I was incorrect about this earlier on.
The problem is with the numerical integration of the splines.
Below is an example based on the data set posted by @johnnybonney.
As a reminder, `u_knots <- c(0.25, 0.5, 0.75)`.
Certain basis splines should integrate to 0, but instead we get some 'bad' zeroes.
```R
> library(splines2)
> fit <- glm(formula = propensity, family = binomial, data = dt)
> problemPropsD0 <- fit$fitted.values[c(11, 41, 330)]
> problemPropsD0
       11        41       330 
0.2935356 0.5781833 0.8948292 
> x1 <- ibs(x = problemPropsD0,
+           knots = u_knots,
+           intercept = TRUE,
+           Boundary.knots = c(0, 1))
> x2 <- ibs(x = c(1, 1, 1),
+           knots = u_knots,
+           intercept = TRUE,
+           Boundary.knots = c(0, 1))
> (x2 - x1)[, 1:3]
                1            2            3
[1,] 6.938894e-18 7.268430e-03 9.396479e-02
[2,] 6.938894e-18 1.387779e-17 2.323968e-03
[3,] 6.938894e-18 1.387779e-17 2.775558e-17
```

Do we want to set a tolerance level?
e.g. anything less than `1e-08` be treated as a 0?

**Comment by a-torgovitsky** [comment] 2019-12-29 14:50
Putting in a hard threshold like that makes me nervous, as it can lead to any number of bizarre outcomes.

The bad zeros here are the e-17 and e-18 ones?
That's below machine tolerance of e-16.
I would expect that these would behave like 0 for all intents and purposes.
Are you saying Gurobi behaves differently with 0 vs 1e-17?

There must be some guidance on how to correctly deal with issues like this somewhere, either from Gurobi, or R...

**Comment by jkcshea** [comment] 2020-01-01 18:58
> The bad zeros here are the e-17 and e-18 ones?
That's below machine tolerance of e-16.
I would expect that these would behave like 0 for all intents and purposes.

You are right about everything there.
[Here, in Gurobi's documentation](https://www.gurobi.com/documentation/8.1/refman/numerics_advanced_user_sca.html) it is written that "Gurobi will treat any constraint coefficient with absolute value under 10^{-13} as zero."

> There must be some guidance on how to correctly deal with issues like this somewhere, either from Gurobi, or R...

[Here](http://files.gurobi.com/Numerics.pdf) is a nice PDF by Gurobi on how to deal with numerical issues.
The suggestions boil down to two things:
1. Reformulating the problem to account for scaling
1. Optimization parameters

We discussed the first approach before, and decided it would be too hard to write code to automate this (but Gurobi has code to do this, though it was not successful when I tried to implement it below).

I tried their suggestions regarding the optimization parameters, and found that:
1. Turning off presolve (`presolve = 0`) allowed the maximization problem to be solved in under 5 minutes.
1. Leaving presolve on, but turning off aggregation (`Aggregate = 0`), also allowed the maximization problem to be solved, but it took 20 minutes.
1. Setting  `AggFill = 0` worked, and is supposed to be faster than just setting `Aggregate = 0`, but it still took about 20 minutes.
1. Setting `NumericFocus` (parameter governing how careful Gurobi is with numerical issues) doesn't resolve anything. 
But it did allow Gurobi to recognize there was a numerical error rather quickly (10--20 seconds).
1. Using the `scaleFlag` argument to automatically (and aggressively) rescale the problem had no effect.
1. Playing with the methods seems useful only if you know which method would perform better.
For example, with just `presolve = 0`, Gurobi uses both the dual simplex and primal simplex methods, returning the results of whichever finishes first.
In our case, the results are obtained by the dual simplex method.
The primal simplex method didn't converge within 40 minutes, so I killed it.

From looking at forums, other users and Gurobi have acknowledged that turning off presolve can eliminate numerical errors, e.g. [here](https://groups.google.com/forum/#!topic/gurobi/feorT4f00Qk).
I'm not seeing a clear rule for when turning off presolve is optimal, so maybe we can't automate that decision.
Maybe let the user decide by providing an option for presolving?

-----------------

Also, another correction regarding the small coefficients in the constraint matrix.
There are two kinds of entries in the constraint matrix:
1. The gamma moments defining the equality constraints
1. The audit grid defining the shape/inequality constraints.

The numerical integration of the B-splines, as discussed above, are responsible for the 'bad zeroes' (i.e. things like 1e-17) in the equality constraints.

However, the bad zeroes in the inequality constraints are because of the variable `prop_indianwhite0`, which has tiny values like `3.207953e-10`.
Interacting that variable with the basis splines results in an even smaller number, and is what is responsible for the coefficient statistics posted earlier [here](https://github.com/jkcshea/ivmte/issues/161#issuecomment-566640825). 

Just thought @johnnybonney may want to know this about the data, in case this is new.

**Comment by a-torgovitsky** [comment] 2020-01-01 23:52
Hmm...this is suggesting to me that we aren't going to be able to find a one-size-fits all solution for these types of problems.

Maybe the solution is to allow the user to pass a list of Gurobi options.
(Maybe a vector of strings? Or a named list? I'm not sure the best way to organize it).
Is that easy to implement?
As part of this, maybe also an "easy" option of `presolve = FALSE` or `TRUE` that augments the list of options?

**Comment by jkcshea** [comment] 2020-01-02 00:35
> As part of this, maybe also an "easy" option of presolve = FALSE or TRUE that augments the list of options?

Sure thing.

> Maybe the solution is to allow the user to pass a list of Gurobi options.
(Maybe a vector of strings? Or a named list? I'm not sure the best way to organize it).
Is that easy to implement?

I think this should be okay, too.
We can use the `...` syntax, I think.
Our use of it will be slightly different from usual, but I suspect it shouldn't be too hard to make things work.

**Comment by a-torgovitsky** [comment] 2020-01-02 01:16
Or maybe a dictionary (list in R?) of option name and value pairs?
Not sure what's better

**Comment by jkcshea** [comment] 2020-01-02 01:33
Oh, that would actually be the easiest to implement, and I've seen that with other packages, too.
So I'll go down that route.

**Comment by jkcshea** [comment] 2020-01-02 03:33
Done!

The option is named `lpsolver.options`, e.g.

```R
args$lpsolver <- "gurobi"
args$lpsolver.options <- list(presolve = 1,
                              method = 1)
```

The function checks that `lpsolver.options` is a list.
If not, an error is returned informing the user that it must be a list, with the names of each item matching the name of the option.

I've done this only for Gurobi, though.
So currently, if the user passes `lpsolver.options` for CPLEX or lpSolveAPI, a warning is thrown out informing the user that `lpsolver.options` is only implemented if the solver is Gurobi.
I will extend this to CPLEX and lpsolveapi.

**Comment by a-torgovitsky** [comment] 2020-01-02 16:04
Perfect!
@johnnybonney this should give you the ability to solve the problem, by just changing the presolve option, right?

**Comment by johnnybonney** [comment] 2020-01-02 18:12
With presolve turned off, the upper and lower bound LP problems are each now solved in ~10 minutes on my machine without any numerical error. However, I noticed that the LP problem for the minimum criterion (which took about 20 seconds with presolve turned on) now also takes about 10 minutes. Is this a trade-off we are just going to have to live with?

Aside from that, this appears to solve the issues with numerical precision. I am going to start tackling some other problems and will let you know if anything odd comes up or if numerical precision issues reappear.

> However, the bad zeroes in the inequality constraints are because of the variable prop_indianwhite0, which has tiny values like 3.207953e-10.

@jkcshea -- thanks for pointing this out. The small values aren't unexpected given the variable, but this is good for me to know. I may decide do some rounding here.

> As part of this, maybe also an "easy" option of presolve = FALSE or TRUE that augments the list of options?

My understanding was that this would be a simple `presolve` argument that a user could feed straight to `ivmte`. If that's the case, this doesn't seem to be implemented yet.

**Comment by jkcshea** [comment] 2020-01-03 01:52
> My understanding was that this would be a simple presolve argument that a user could feed straight to ivmte. If that's the case, this doesn't seem to be implemented yet.

Ah you're right, I had forgotten to do that.
I've just added that in.

If the presolve parameter is declared in both `lpsolver.options` and `lpsolver.presolve`, then the function checks to make sure they match.

**Comment by johnnybonney** [comment] 2020-01-03 14:45
A quick update: I ran the entire `ivmte` procedure for the example I had sent with presolve turned off. I got approximately equivalent bounds to what @jkcshea found earlier using CPLEX ([in this comment](https://github.com/jkcshea/ivmte/issues/161#issuecomment-566505866)):
```
Bounds on the target parameter: [0.007319054, 0.01461555]
```
One significant difference I should mention is that the total run-time was ~8 hours (as opposed to the 40 minutes that it took CPLEX). I am assuming that I just have to make this trade-off between run-time and numerical issues?

[I would just install and use CPLEX, but I have already spent many hours unsuccessfully trying to set up CPLEX with R. However, if an 8-hour run-time with Gurobi is the alternative, I might invest more time trying to set up CPLEX.]

**Comment by a-torgovitsky** [comment] 2020-01-03 14:49
Playing with some of the parameters above might also help.
By the way, are you using Gurobi 9 yet? The new versions are often substantially better than the old ones, and it's an easy thing to try.

**Comment by johnnybonney** [comment] 2020-01-03 14:53
Yeah, I have been using Gurobi 9. I will play around with the Gurobi options to see if I can speed things up that way.

**Comment by a-torgovitsky** [comment] 2020-01-03 14:58
Is it still the case that running through Gurobi directly as opposed through `ivmte` is much faster? Or has that been resolved?

**Comment by jkcshea** [comment] 2020-01-03 16:19
The long run-time with Gurobi may partly be because of this:

> I noticed that the LP problem for the minimum criterion (which took about 20 seconds with presolve turned on) now also takes about 10 minutes. Is this a trade-off we are just going to have to live with?

Do we want to do anything about this?

It won't be hard to allow the user to submit two different lists of options, one for the minimum criterion LP problem, and another for the bounds.

**Comment by a-torgovitsky** [comment] 2020-01-03 17:28
I guess that's a reasonable bandaid for now.

@johnnybonney do you think you could play around with your specification a bit?
It would be nice to know what about it leads to computational difficulties.

**Comment by johnnybonney** [comment] 2020-01-03 21:02
> Is it still the case that running through Gurobi directly as opposed through `ivmte` is much faster? Or has that been resolved?

It seems to be resolved. I will check periodically to see if it resurfaces.

When double-checking this, though, I did notice an instance when Gurobi standalone took (much) longer than R-Gurobi. (This is for the first audit iteration of the lower bound LP problem, with presolve turned off.) In case it is useful to know, below is the discrepancy (which begins after iteration 11800).

R-Gurobi gives:
```
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0      handle free variables                          1s
     268   -2.5406903e+30   9.502795e+34   2.540690e+00      5s
     429   -1.2288078e+29   1.167842e+36   1.228808e-01     11s
       .
       .
   11800   -3.6879292e-01   2.120352e-02   4.782545e+11    433s
Warning: 1 variables dropped from basis
Warning: switch to quad precision
   11999   -3.6847595e-01   0.000000e+00   9.903646e+01    447s
       .
       .
Solved in 13581 iterations and 554.69 seconds
Optimal objective -3.803053335e-01
Warning: unscaled primal violation = 0.000519375 and residual = 0.00131518
```
While Gurobi standalone gives
```
Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0      handle free variables                          1s
     429   -1.2288078e+29   1.167842e+36   1.228808e-01     8s
       .
       .
   11800   -3.6879292e-01   2.120352e-02   4.782545e+11    404s
Warning: 1 variables dropped from basis
Warning: switch to quad precision
Warning: 1 variables dropped from basis
   11945   -3.6407212e-01   0.000000e+00   4.133724e+02    416s
       .
```
At this point, Gurobi standalone stops giving the same output as R-Gurobi did and goes on to iterate for over an hour (I killed it, since it wasn't close to converging).

> @johnnybonney do you think you could play around with your specification a bit?
It would be nice to know what about it leads to computational difficulties.

Yes, definitely. I will let you know what I find.

**Comment by a-torgovitsky** [comment] 2020-01-04 16:16
That's strange -- can you replicate this behavior reliably?
@jkcshea could you take a quick look at the Gurobi forums to see if anyone has discussed a difference between Gurobi standalone and the R API before?
It could be a bug...but at least it would be good to know what exactly the R API is doing differently.

**Comment by jkcshea** [comment] 2020-01-04 17:35
There seems to have been only one post along such lines, and that was from me a while ago ([here](https://support.gurobi.com/hc/en-us/community/posts/360043503952-R-API-behaving-differently-from-Gurobi-via-command-line)).
The response from Gurobi was that we were probably running into numerical issue due to a badly scaled model.

I know with the default `method` parameter, Gurobi can return different results across multiple runs, as explained [here](https://www.gurobi.com/documentation/6.0/refman/method.html).
But this seems to require a non-unique solution to the LP problem, and is unlikely to explain what @johnnybonney posted.

**Comment by a-torgovitsky** [comment] 2020-01-04 23:59
Ok but that was for the .lp model format, right?
Now this problem is still coming up with .mps?

**Comment by jkcshea** [comment] 2020-01-05 03:51
> Now this problem is still coming up with .mps?

Yeah, it looks to be the case.
When `debug = TRUE`, the LP problems are saved as .mps files.
Those .mps files are what we've been feeding standalone Gurobi.

If @johnnybonney  can replicate this, then I can post something to the Gurobi support page.
Not sure how we can generate a simpler example, though...

**Comment by a-torgovitsky** [comment] 2020-01-05 16:44
If you have the mps and can show it solves differently in R and the
standalone, then I think you can just give them the mps file.

Maybe there is a good reason for the discrepancy but if so it would be good
to know why and what the implications are, and it doesn't seem to be
documented

**Comment by johnnybonney** [comment] 2020-01-06 16:42
[Here is a Dropbox link to the .mps file](https://www.dropbox.com/s/q3xuxi8jffxagv5/lpMin.mps?dl=0) (it is too big to upload to GitHub -- let me know if the link is problematic).

If I load it into R and solve it via the Gurobi API, it solves in 13581 iterations (in roughly 10 minutes). If I try to solve it with Gurobi standalone, it has the same issue that I showed in my earlier comment.

**Comment by jkcshea** [comment] 2020-01-10 21:38
Still no response from the support portal.
But the previous moderator (who seems to be the only other person 'subscribing' to my earlier thread) was last active 5 months ago, so I'll repost.

**Comment by jkcshea** [comment] 2020-09-25 02:21
No response from Gurobi, but I'm happy to say that this issue is no longer happening, for whatever reason.
Solving the problem in R via the API gives me the exact results as feeding the model directly to Gurobi.

Attached is the example, just for convenience/documentation.
I scaled the variable `prop_indianwhite0` is scaled by `1e3` to avoid scaling issues.
[dinkelman_example_updated.zip](https://github.com/jkcshea/ivmte/files/5280162/dinkelman_example_updated.zip)

The overhaul of the audit procedure may have had a role to play.

**Closed by jkcshea** 2020-09-25 02:21 UTC
Labels: question

**Comment by a-torgovitsky** [comment] 2020-09-25 15:00
Interesting. Yes since the audit procedure has changed, who knows what happened. Glad it is fixed! Thanks!
