### ISSUE TITLE
Where are these extra moments coming from?

### ISSUE THREAD

**Issue by johnnybonney** [jkcshea/ivmte#153] opened 2019-11-15 18:03 UTC
Maybe this is a silly question -- but I noticed that the number of moments calculated is sometimes greater than what I would expect (given the specification). See the following example:

```
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args_test <- list(
  data = dt,
  propensity = d ~ factor(z),
  m0 = ~u,
  m1 = ~u,
  target = "ate",
  lpsolver = "gurobi"
)

args_test$ivlike <- y ~ d + factor(z) + d:factor(z) # would expect 8 moments
test_res <- do.call(ivmte, args_test)
```
```
Obtaining propensity scores...
Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...
Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
    Moment 9...
    Moment 10...
    Moment 11...
Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.08689983
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2744784, -0.2744784]
```
Oddly, I somehow have 11 moments, three more than expected.
I now manually factor out the moments that I would expect to be included (based on the `lm` output for that specification):
```
args_test$ivlike <- y ~ d + I(z==2) + I(z==3) + I(z==4) + d:I(z==2) + d:I(z==3) + d:I(z==4)
test_res <- do.call(ivmte, args_test)
```
```
Obtaining propensity scores...
Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...
Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.08689983
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2744784, -0.2744784]
```

In both cases, the results are the same, so I am not too concerned that the results are wrong -- but why does it say I have three extra moments in the first case?

--------
Also, if I drop `d` from the specification (using `y ~ factor(z) + d:factor(z)`), I would expect things to still work the same way (the moments will change slightly -- e.g. the coef. on `d` will be swapped for the excluded interaction, `factor(z)1:d`, but the information should be the same), but it now says I have 14 moments (6 more than expected), and I get different bounds than the prior two specifications:
```
args_test$ivlike <- y ~ factor(z) + d:factor(z)
test_res <- do.call(ivmte, args_test)
```
```
Obtaining propensity scores...
Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...
Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
    Moment 9...
    Moment 10...
    Moment 11...
    Moment 12...
    Moment 13...
    Moment 14...
Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.1277638
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2825699, -0.2825699]
```
Any clarity would be useful. Given our discussion in #151, I want to be extra careful that I understand what moments I am feeding `ivmte`.

**Comment by jkcshea** [comment] 2019-11-15 22:39
Not a silly question, it looks to be related to #152.
That is, I can no longer recreate the results you showed above, and am now always getting 8 moments.

Also, if you ever want to inspect the moments, throw this into R:
```
lapply(test_res$sset, function(x) c(x$ivspec, x$beta))
```
The first entry (`$ivspec`) indexes the specification.
The second entry (`$beta`) displays the regression coefficient.
For example
```R
> lapply(test_res$sset, function(x) c(x$ivspec, x$beta))
$s1
            (Intercept) 
  1.0000000   0.4094129 

$s2
             factor(z)2 
 1.00000000 -0.08688042 

$s3
           factor(z)3 
 1.0000000 -0.1530523 

$s4
           factor(z)4 
  1.000000  -0.260537 

$s5
             factor(z)1:d 
  1.00000000  -0.07577249 

$s6
             factor(z)2:d 
  1.00000000  -0.01619524 

$s7
             factor(z)3:d 
  1.00000000   0.01011048 

$s8
             factor(z)4:d 
  1.00000000   0.06018317 
```

**Comment by johnnybonney** [comment] 2019-11-18 16:22
Great, thanks! I now always have 8 moments. A couple of follow-up questions:

1. The previous estimates are unchanged, so `y ~ factor(z) + d:factor(z)` still gives a different estimate than the other two specifications. As I mentioned above, although the moments change slightly, the information should be exactly the same, so should this be happening?
2. Thanks to the new output, I am now seeing that (in all three specifications) only four of the moments are independent. Given that the moments should essentially give E[Y|D=d, Z=z] for d in {0, 1} and z in {0, 1, 2, 3}, I would expect all eight moments to be independent, so are things working correctly?

Here is the output:
```
> args_test$ivlike <- y ~ d * factor(z)
> test_res <- do.call(ivmte, args_test)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
    Independent moments: 4 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.08689983
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2744784, -0.2744784]
```

**Comment by johnnybonney** [comment] 2019-11-18 16:38
With some further exploration of problem 2, I see that when I specify the MTRs as `~u + I(u^2) + I(u^3)`, it says I have eight independent moments:
```
> args_test$ivlike <- y ~ factor(z) + d:factor(z)
> args_test$m1 <- args_test$m0 <- ~u + I(u^2) + I(u^3)
> test_res <- do.call(ivmte, args_test)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...
    Integrating terms for control group...
    Integrating terms for treated group...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Moment 7...
    Moment 8...
    Independent moments: 8 

Performing audit procedure...
    Generating audit grid...
    Generating initial constraint grid...

    Audit count: 1
    Minimum criterion: 0.01427195
    Obtaining bounds...
    Violations: 0
    Audit finished.

Bounds on the target parameter: [-0.2076925, -0.2076925]
```

Using a quadratic yields 6 independent moments. It seems like there is some restriction that the number of "independent" moments cannot exceed the number of parameters to be estimated. Is this intentional?

**Comment by jkcshea** [comment] 2019-11-19 04:01
> It seems like there is some restriction that the number of "independent" moments cannot exceed the number of parameters to be estimated. Is this intentional?

Hm, maybe what I didn't wasn't the best.
The number of independent moments are calculated using the LP equality constraints.
So if you have a total of $k_1 + k_0$ terms in the MTRs, and you have $|S|$ IV-like components, then there are at most $\max\{k_1 + k_0, |S|\}$ linearly independent moment conditions.
So what is being reported is the effective number of independent moment conditions.

This is why you were observing the number of independent moments change with the MTR specification, and also why that number cannot exceed the number of parameters to be estimated.

Is there a better way? Or a better message?

> The previous estimates are unchanged, so y ~ factor(z) + d:factor(z) still gives a different estimate than the other two specifications. As I mentioned above, although the moments change slightly, the information should be exactly the same, so should this be happening?

Still haven't cracked this yet.
I thought it may be due to statistical noise, but it seems like it is not...

**Comment by a-torgovitsky** [comment] 2019-11-19 15:36
Didn't you do something like this for the point identified case?
Where you remove extra moments in order to be able to do the two-step estimation?
Isn't this just the same thing?

The number of parameters shouldn't affect the number of independent moments that are counted.

**Comment by jkcshea** [comment] 2019-11-19 22:37
> Didn't you do something like this for the point identified case?
Where you remove extra moments in order to be able to do the two-step estimation?
Isn't this just the same thing?

Yes, it is, I should've thought of doing that.
this has been implemented.

----------------------

Regarding the second part of [this](https://github.com/jkcshea/ivmte/issues/153#issue-523611683)
and
> y ~ factor(z) + d:factor(z) still gives a different estimate than the other two specifications. As I mentioned above, although the moments change slightly, the information should be exactly the same, so should this be happening?

I've checked the code, and it doesn't look like it's doing anything wrong.
I believe this is just an issue with overidentification, but @a-torgovitsky may have a better idea.

Suppose we have an LP problem in R^3, and we have 3 linear equality constraints that intersect at point A*.
Hopefully the following picture is decipherable.

![New Doc 2019-11-19 15 49 15_1](https://user-images.githubusercontent.com/8278206/69190022-2c956c00-0ae5-11ea-8151-22515b608b67.jpg)

**Setting 1**

Suppose we project this into R^2 (e.g. your MTRs should have 3 terms in total, but you misspecified your model so it only has 2).
We'll end up with an infeasible problem, i.e. we need to find a single point that satisfies all three intersections.

![New Doc 2019-11-19 15 49 15_2](https://user-images.githubusercontent.com/8278206/69191187-9ca4f180-0ae7-11ea-9196-ecc3c5f8c1d9.jpg)

To deal with this, we calculate the minimum criterion, which involves finding some point in R^2 that minimizes the sum of the violations of the equality constraints.
Since `criterion.tol = 0` by default, the solution to minimizing the criterion will be the solution to the bounding problem as well.

**Setting 2**

Suppose I updated equality constraint 1 so that it is "flatter".
Specifically, I rotated constraint 1 a little around its axis of intersection with constraint 3.
In R^3, the point of intersection for all three planes is still A*.
However, in the projection to R^2, line C1 would shift out to, say, the dashed line.

![New Doc 2019-11-19 15 49 15_3](https://user-images.githubusercontent.com/8278206/69191203-a3336900-0ae7-11ea-8ebb-fa1dd5de8dc1.jpg)

Hence, if you were to minimize the criterion in this setting, you'd get something different from **Setting 1.**
But again, if you had stayed in R^3, the solution is still A*.

So I think that when we project equally informative constraints into lower dimensions, there is no guarantee that the solutions to these lower-dimensional LP problems will be the same.

**Comment by jkcshea** [comment] 2019-11-20 14:13
> Didn't you do something like this for the point identified case?
Where you remove extra moments in order to be able to do the two-step estimation?
Isn't this just the same thing?

While performing the CRAN checks again, I realized that GMM cannot be performed if the user passes the `subset` argument.
I'm not seeing a way around this, and just wanted to confirm this is indeed the case.

**Comment by a-torgovitsky** [comment] 2019-11-20 14:51
You mean `point = TRUE` and `subset` cannot be passed as the same time?
Why is that?

**Comment by a-torgovitsky** [comment] 2019-11-20 14:59
Regarding the longer post (with the _very impressive_ 3d drawings!), I'm a bit unclear as to what the problem is from @johnnybonney 's previous posts.

Could you give me the MWE again?

In particular, this part doesn't make sense to me:
>The previous estimates are unchanged, so y ~ factor(z) + d:factor(z) still gives a different estimate than the other two specifications. As I mentioned above, although the moments change slightly, the information should be exactly the same, so should this be happening?

If the moments change, then how is the information still the same?

**Comment by johnnybonney** [comment] 2019-11-20 16:04
Sure, I am happy to rehash my concern.

Before using `ivmte`, I want to address how moments can change but information can stay the same. The simple case to think about is information from the OLS estimand:
1. `y ~ d` is going to give you two moments: E[Y|D=0] and E[Y|D=1] - E[Y|D=0].
2. `y ~ 0 + I(1-d) + d` will give you two moments: E[Y|D=0] and E[Y|D=1]. 

These moments aren't the same, but they contain the same exact information. Accordingly, you cannot match one without matching the other.

In a similar fashion, `y ~ d + factor(z) + d:factor(z)` and `y ~ factor(z) + d:factor(z)` are going to give two slightly different sets of moments. However, the information (if my above intuition is correct) is the same: at the end of the day, they both give E[Y|D=d, Z=z] for d \in {0, 1} and z \in Z.

Below is the example. Note that this problem is specific to over-identified cases (which I am not particularly interested in running myself). I primarily wanted to check that the moments are being calculated as expected.

```
## setup
library(data.table)
library(ivmte)

set.seed(1001)
N <- 2000

dt <- data.table(
  id = 1:N,
  u = runif(N),
  z = sample(1:4, N, replace = T),
  epsilon = rnorm(N, sd = .1)
)

dt[, p := (z == 1)*0.12 + (z == 2)*0.29 + (z == 3)*0.48 + (z == 4)*0.78]
dt[, d := as.integer(u <= p)]
dt[, y0 := 0.9 - 1.1*u + 0.3*u^2]
dt[, y1 := 0.35 - 0.3*u - 0.05*u^2]
dt[, y := y1*d + y0*(1 - d) + epsilon]

args_test <- list(
  data = dt,
  propensity = d ~ factor(z),
  target = "ate",
  m0 = ~u, m1 = ~u,  # MTE is linear, so we are over-identified
  lpsolver = "gurobi",
  m0.lb = -Inf, m0.ub = Inf,
  m1.lb = -Inf, m1.ub = Inf,
  noisy = F
)

args_test$ivlike <- y ~ d + factor(z) + d:factor(z)
test_res <- do.call(ivmte, args_test)

# bounds: [-0.2744784, -0.2744784], criterion: 0.0869

# now replace information set with something that should be equivalent
args_test$ivlike <- y ~ factor(z) + d:factor(z)
test_res <- do.call(ivmte, args_test)

# bounds: [-0.2825699, -0.2825699], criterion: 0.0793
```
The bounds change, though the information is equivalent.

It is worth noting that if `m0` and `m1` are cubic or quartic (so that we are no longer over-identified), both information sets give exactly equivalent bounds and minimum criteria, so this "problem" goes away.

What @jkcshea is saying makes sense to me -- if I understand correctly, although the information is the same, once we have to add extra flexibility (i.e. minimum criterion is not 0), there is no guarantee that such flexibility is equivalent across the two specifications.

**Comment by a-torgovitsky** [comment] 2019-11-20 16:30
Ok, I think I understand now.

This is a good example:
>y ~ d is going to give you two moments: E[Y|D=0] and E[Y|D=1] - E[Y|D=0].
y ~ 0 + I(1-d) + d will give you two moments: E[Y|D=0] and E[Y|D=1].

I believe the reason one gets different results is because the criterion used in the partial identification case is equally weighted.
So, weighting E[Y | D = 0] and E[Y | D = 1] - E[Y | D = 0] equally is different than weighting E[Y | D =0] and E[Y | D = 1] equally.
This is also why it is no longer a problem when the model is flexible, so that all moments are exactly replicated.

If I am correct, then this should also be a problem in the point identified case _if using the identity weighting matrix_ and the criterion is not zero.
However, the optimal weighting should fix this.
It would be good to check this reasoning if possible.

Unfortunately, we don't (and won't any time soon) have an "optimal" weighting for the partially identified case, so there's no fix for this.

@jkcshea does that intuition conform with your figures?

**Comment by jkcshea** [comment] 2019-11-20 20:31
> You mean point = TRUE and subset cannot be passed as the same time?
Why is that?

This is because some moments exclude certain observations.

For example, suppose I had two IV-like specifications, each one with 2 components.
For one specification, I use the full sample. And for the other, I only use the female subsample.
So the male sample has to satisfy only two moment conditions, whereas the female sample must satisfy 4.

Or is there a way around this? e.g. place greater weight on moments that use the full sample?

-----------------------------

> If I am correct, then this should also be a problem in the point identified case if using the identity weighting matrix and the criterion is not zero.
However, the optimal weighting should fix this.
It would be good to check this reasoning if possible.

Trying this on `ivmte` suggests this to be true.
As you predicted, there are differences under point identification and identity weighting.
This difference almost disappears under efficient weighting.

------------------

> @jkcshea does that intuition conform with your figures?

I hadn't thought about the weights, but the above seems to suggest it is a better explanation.

What I had in mind is perhaps more suitable to explaining what is happening when the model is **both** overidentified and misspecified.
Following from @johnnybonney's example:

> y ~ d is going to give you two moments: E[Y|D=0] and E[Y|D=1] - E[Y|D=0].
y ~ 0 + I(1-d) + d will give you two moments: E[Y|D=0] and E[Y|D=1].

Suppose the MTRs were just constants, so there are only two parameters to estimate, $\mu_0$ and $\mu_1$.
To make life easier, suppose there is no selection.

So what @johnnybonney is suggesting may look something like this:

![New Doc 2019-11-20 13 23 45_1](https://user-images.githubusercontent.com/8278206/69274769-b1918b80-0ba0-11ea-92ef-a4cf54023d34.jpg)

![New Doc 2019-11-20 13 23 45_2](https://user-images.githubusercontent.com/8278206/69274782-b6eed600-0ba0-11ea-81c5-726a1c87b646.jpg)

Both sets of constraints yield the same solution.

Now suppose we misspecify the model by assuming that $\mu_0 = 0$
Clearly, both models become infeasible since they will violate the constraint $E[Y |D = 0] = 1$.
But the first picture would suggest that $\mu_1 = 2$, whereas the bottom picture would suggest $\mu_1 = 1$.
Somewhat of an extreme/contrived example, but perhaps shows how two equally informative sets of constraints need not yield the same solution when the model is misspecified.

**Comment by a-torgovitsky** [comment] 2019-11-20 21:21
Regarding point identification and subsetting, I don't understand.
There is nothing fundamentally different about point and partial identification cases here.
In both cases we construct a matrix \Gamma, and then try to equate
\Gamma \theta = \beta
where \beta are the estimated IV--like estimands, and \theta are the basis parameters.
Why does being able to make this equality hold exactly or not (i.e. point identification or partial identification) interact with subsetting?

----

That's a great example.
I think it's getting at the same thing as the weight interpretation.
Essentially, if we don't exactly match the moments, then we need to define a norm between the predicted moments and the estimated moments.
Depending on how that norm is defined (the weighting) and/or the nature of the misspecification (your constraint m0 = 0), we might end up at a different point.
I think that's completely to be expected, and there isn't anything we can do about it.
The fact that it also happens in GMM with identity weighting is reassuring to me.
In principle, this is an "estimation issue" in the sense that if the model is correctly specified in the population (which is always assumed in the background), then eventually we will fully match the moments and so there won't be any question of how we measure deviations from them.

**Comment by jkcshea** [comment] 2019-11-21 01:25
> There is nothing fundamentally different about point and partial identification cases here.
In both cases we construct a matrix \Gamma, and then try to equate
\Gamma \theta = \beta

Hm, yes that makes sense.

So just to confirm: in your writeup, it's no problem for the components of these means to correspond to different subpopulations:

![image](https://user-images.githubusercontent.com/8278206/69291941-4bb9f980-0bca-11ea-9a02-5707683843bc.png)

Specifically, different rows of E[G_i] may correspond to different subsets.
Likewise, different rows/columns of the weight matrix will correspond to different subsets.

It looks like the difference in number of observations used to estimate each moment will be accounted for by the weight matrix, which is nice.

**Comment by a-torgovitsky** [comment] 2019-11-21 01:34
Yes that's right, I don't see why it would matter

For example, suppose we use Y as a moment but subset on S = 1.
It is the same as implementing the moment
E[Y 1[S = 1]]
(The P[S = 1] cancels out from both the IV--like estimand and the weighting expressions.)

There's nothing that prevents us from having both
E[Y]
and
E[Y 1[S = 1]]
is there?

**Comment by jkcshea** [comment] 2019-11-21 01:37
Nope, nothing at all.
I just have to make some adjustments, then this will be good to go.

**Comment by jkcshea** [comment] 2019-11-24 04:09
I noticed that specifications involving only splines can be problematic when it comes to point identification.
Here is one example:
```R
args <- list(data = ivmteSimData,
             ivlike =  c(y ~ z + x,
                         y ~ d + x,
                         y ~ d | z),
             target = "ate",
             m0 = ~ 0 + uSplines(degree = 0, knots = c(.25, .5)),
             m1 = ~ 0 + uSplines(degree = 0, knots = c(.25, .5)),
             propensity = d ~ z + x,
             point = TRUE,
             noisy = TRUE)
r <- do.call(ivmte, args)
```
We have 8 moment conditions, but only 7 of which are linearly independent.
But the E[G] matrix (which is 8 x 6) only has rank 4.
I've checked the matrices, and they all look to be constructed correctly.

This example seems to make sense, though.
In each of the $G_i$ matrices, there are two halves: the columns for $D = 0$ and $D = 1$.
For each of these halves, you only need to know two of the columns to figure out what the third one must be.

Is this unexpected or suspicious?
If not, would you like to warn the user about this (e.g. they may be confused when they see that they have more linearly independent moment conditions than unknowns, yet GMM fails)?

**Comment by a-torgovitsky** [comment] 2019-11-24 14:53
Hmm...not sure to me what's going on here.
Do you have a more minimal MWE? Maybe with fewer IV like estimands?

**Comment by jkcshea** [comment] 2019-11-25 02:57
Sorry, I realize now that what I posted above is incorrect.
The problem seems to be related to subsetting, though.

Here is a simpler MWE, albeit it still has 6 IV-like estimands:
```R
> args <- list(data = ivmteSimData,
+              ivlike =  c(y ~ z + x,
+                          y ~ d + x),
+              target = "ate",
+              m0 = ~ 0 + uSplines(degree = 0, knots = c(.25, .5)),
+              m1 = ~ 0 + uSplines(degree = 0, knots = c(.25, .5)),
+              propensity = d ~ z + x,
+              point = TRUE,
+              noisy = TRUE)
> r <- do.call(ivmte, args)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Independent moments: 4 
[1] "Rank of G"
[1] 4
```
The number of independent moment conditions matches the rank of E[G], which is good.

Now let's include subsetting for the first IV-like specification.
```R
> args[["subset"]] <- l(z > 1, )
> r <- do.call(ivmte, args)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Independent moments: 6 
[1] "Rank of G"
[1] 5
```
This alteration buys us two additional independent moment conditions.
But now the rank of E[G] no longer matches the number of independent moments.
If I change the knots of both splines to `c(0.75, 0.85)`, the E[G] matrix is only rank 4.

I checked several of the matrix calculations by hand to confirm they make sense, and they do.
But I can't quite figure out an intuitive explanation for why this is happening (i'm assuming it's actually very simple...).

**Comment by jkcshea** [comment] 2019-11-25 03:27
I suspect it has something to do with how the subsetting reduces the variation in the data.
So even though the moments are all independent, the data just isn't rich enough to extract the information.

**Comment by a-torgovitsky** [comment] 2019-11-25 21:22
Hmm...
In general it makes sense to me that conditioning on Z would increase the number of moments.
It's essentially using a conditional moment.

Can you remind me what you are doing to compute "Independent moments"?

I suppose that needs to differ from "Rank of G" because the rank of G is also influenced by the m0 and m1 specifications? Is that the crux of the issue?

I think what might be happening here is that you have parameters in the m0 and/or m1 specification that are just hopefully unidentified. There is no info in the data on them.
What happens if you add knots like (.97, .98, .99)? These should yield parameters with basically no representation in the data.

**Comment by jkcshea** [comment] 2019-11-26 00:29
> Can you remind me what you are doing to compute "Independent moments"?

[Here](https://github.com/jkcshea/ivmte/issues/138#issuecomment-548628678) we discuss about using an eigendecompositoin of H'H, where each row of H is defined according to 
![image](https://user-images.githubusercontent.com/8278206/69586387-0cafed80-0fa8-11ea-9fdd-3a6b9ff8dfbd.png)
The rank of H'H is our count of number of moments, and the eigendecomposition allows us to drop any unnecessary ones when performing GMM.
The $\theta$ turns out not to be important for calculating the rank.

Another way of counting is to compare the `s(d, x, z)`.
That is, for each component, I stack `s(0, x, z)` and `s(1, x, z)`.
I then column-bind this `2 * n` long vector (`n` is sample size) across all IV-like estimands.
The rank of this matrix corresponds with the method described above.

> I suppose that needs to differ from "Rank of G" because the rank of G is also influenced by the m0 and m1 specifications? Is that the crux of the issue?

Yes, that seems to be the case.

> I think what might be happening here is that you have parameters in the m0 and/or m1 specification that are just hopefully unidentified. There is no info in the data on them.

Ah yes, that seems to be the simple explanation I was unable to reach,

By subsetting the data to `z > 1`, the propensity scores in the sample range between `0.5` and `0.8`.
So for the original knots, `c(0.25, 0.5)`, we have no data for the intervals `[0, 0.25]` and `[0.25, 0.5]`.
Here, E[G] had rank 5.

For the second pair of knots `c(0.75, 0.85)`, we have no data on the interval `[0.85, 1]`
Here, E[G] had rank 4.

For your suggested knots of `c(0.97, 0.98)`, we have no data on the last two intervals.
The rank of E[G] decreases to 3.

In all these cases, we count 6 independent moments.

The part that is still unclear to me is the relationship between the number of intervals we have data on, and the rank of E[G].
In two of the examples above, we only had data on one of the three intervals.
But in one case, the rank of E[G] was 3, and in the other it was 4.

**Comment by a-torgovitsky** [comment] 2019-11-26 17:36
Ok, so it looks like the problem here is that simple moment counting exercises don't cut it for point identification when there are splines, because splines can have parameters that are only point identified if there is local information.

I think as a solution we do this:
1) Continue to report number of independent moments
2) Also report the rank of G --- I believe this is the matrix "Gamma" in the R paper, right? So let's call it the rank of the Gamma matrix.
3) If not point identified and the m0 and m1 specification contain splines, then print a warning about moment counting exercises being potentially unreliable. If it's too hard to determine whether m0 and m1 contain splines, then we could just print this warning whenever there is a lack of point identification.

**Comment by jkcshea** [comment] 2019-11-26 22:29
How does this look?
```R
> r <- do.call(ivmte, args)

LP solver: Gurobi ('gurobi')

Obtaining propensity scores...

Generating target moments...

Generating IV-like moments...
    Moment 1...
    Moment 2...
    Moment 3...
    Moment 4...
    Moment 5...
    Moment 6...
    Independent moments: 6 
Error: GMM system is underidentified: there are 6 unknowns, 
but the Gamma matrix has rank 4. The previous count of 
6 independent moments becomes unreliable when m0 or m1 
includes splines. Either adjust the IV-like specifications, 
or adjust m0 and m1.
```

**Comment by a-torgovitsky** [comment] 2019-11-26 23:46
Looks good thanks!

**Comment by jkcshea** [comment] 2019-11-26 23:52
Great!
Then once I'm done fixing this other parsing issue I came across (will open an issue afterward, for the sake of documentation), then I'll resubmit to CRAN.

**Closed by jkcshea** 2019-11-26 23:52 UTC
Labels: question
